<div class="mini-login form-custom">
    <p class="ou"><?php echo $this->__('Or'); ?></p>
    <p class="connect"><?php echo $this->__('Connect in your customer space'); ?><em>**</em> :</p>
    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="mini-login">
        <?php echo $this->getBlockHtml('formkey'); ?>
        <div class="block-content-login">
            <?php echo $this->getBlockHtml('formkey'); ?>
            <ul class="form-list">
                <li>
                    <label for="email" class="required"><?php echo $this->__('Email Address') ?></label>
                    <div class="input-box">
                        <input type="text" name="login[username]" value="" id="email" class="input-text form-control required-entry validate-email" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Email Address')) ?>" />
                    </div>
                </li>
                <li>
                    <label for="pass" class="required"><?php echo $this->__('Password') ?></label>
                    <div class="input-box">
                        <input type="password" name="login[password]" class="input-text form-control required-entry validate-password" id="pass" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Password')) ?>" />
                    </div>
                </li>
            </ul>
            <div class="actions">
                <button type="submit" class="button btn btn-success btn-right"><span><span><?php echo $this->__('Submit') ?></span></span></button>
            </div>
        </div>
    </form>
    <script type="text/javascript">
        var dataForm = new VarienForm('mini-login', true);
    </script>
</div>
<p class="etoile"><?php echo $this->__('mini_login_p_etoile'); ?></p>