<div class="sur-trois-blocks container-fluid">
   <div class="trois-blocks row">
   	    <a href="<?php echo $this->getUrl('valorisation-de-l-enseignement'); ?>">
   	      <img src="<?php echo $this->getSkinUrl('images/media/valoriser.jpg'); ?>" alt="<?php echo $this->__('Volorisation de l\'enseignement'); ?>" />
   	    </a>
   	    <a href="<?php echo $this->getUrl('developpement-de-la-collaboration'); ?>">
			<img src="<?php echo $this->getSkinUrl('images/media/developper.jpg'); ?>" alt="<?php echo $this->__('Développement de la collaboration'); ?>" />
   	    </a>
   	    <a href="<?php echo $this->getUrl('classflow'); ?>">
			<img src="<?php echo $this->getSkinUrl('images/media/classflow.jpg'); ?>" alt="<?php echo $this->__('Classflow et formation à distance'); ?>" />
   	    </a>
   </div>
</div>