<?php $_footer = $this->getAllNews(); ?>

	<div class="footer container-fluid">
	<div class="row footer-1">
		<div class="footer-1-titre row"><span>Pro</span>Interactive</div>
		<div class="footer-1-txt row">
		     Ipsum dolor sit amet, consectetur adipiscing elit. Etiam ligula velit, euismod eu quam mattis, fringilla hendrerit ante. Praesent sit amet felis vitae diam suscipit scelerisque at nec enim. Nullam porttitor odio sed diam auctor, in imperdiet eros faucibus. Quisque suscipit pellentesque lacus, mattis commodo dui ullamcorper sed. Nulla tellus nisl, interdum at mollis eu, mattis sed ligula. Phasellus efficitur consequat massa, nec viverra mi lacinia in.
        </div>
	</div>
	<div class="row footer-2">

	   <div class="liens-footer">
	        <div class="fleche-footer"></div>
	        <div class="col-md-6 col-sm-12 ">
			    <div class="col-liens col-md-4 col-sm-3  col-xs-6 col-md-offset-0 col-sm-offset-1">
			    	<ul>
			    		<li>ACTIVEBOARD</li>
			    		<li>Board Only</li>
			    		<li>Mount System</li>
			    	</ul>
			    </div>
			    <div class="col-liens col-md-4 col-sm-3 col-xs-6 col-md-offset-0 col-sm-offset-1 ">
			       <ul>
			    		<li>ACTIVEPANEL</li>
			    		<li>65 Inch</li>
			    		<li>70 Inch</li>
			    	</ul>
			    </div>
			    <div class="col-liens col-md-4 col-sm-3 col-xs-6 col-md-offset-0 col-sm-offset-1">
			    	<ul>
			    		<li>VISUALISER</li>
			    		<li>Actiview 324</li>

			    	</ul>
			    </div>
		    </div>
		    <div class="col-md-6 col-sm-12 liens-newsletter-prome">
			    <div class="">
				    <div class="col-liens col-md-4 col-md-offset-2 col-sm-3 col-sm-offset-1 col-xs-6">
				    	<ul>
				    		<li>INFORMATION</li>
				    		<li>About Us</li>
				    		<li>Contact Us</li>
				    		<li>My Acount</li>
				    		<li>Terms & Conditions</li>
				    	</ul>
				    </div>
				    <div class="col-liens col-md-6 col-sm-6 col-md-offset-0 col-sm-offset-1 ">
				    	<ul>
				    		<li>NEWSLETER SIGNUP</li>
				    	</ul>

				    	<div class="newsletter-footer col-md-12">
				    	    <div class="ok-news-letter"></div>
				    		<input type="texte" name="newsletter" class="newsletter" placeholder="Your email adress">	    
				    	</div>
				    	<div class="footer-help col-md-12"></div>
				    	<div class="footer-logo col-md-12"></div>
				    </div>
			    </div>
			    <div class="row col-md-10 col-md-offset-2 col-sm-12 footer-payment">
			    	<div class="footer-mastercard col-md-2 col-sm-2 col-md-offset-0 col-sm-offset-1 col-xs-6 col-xs-offset-0"></div>
			    	<div class="footer-visa col-md-2 col-sm-2 col-xs-6"></div>
			    	<div class="footer-paypal col-md-3 col-sm-3 col-xs-6"></div>
			    	<div class="footer-gopay col-md-4 col-sm-3 col-xs-6"></div>
			    </div>
		    </div>
		</div>

	</div>
	<div class="row footer-3"><div class="copyright">Copyright <?php echo date('Y');?></div></div>
</div>
