<?php $_menuentete = $this->getAllNews(); ?>

	<div class="sur-header">
	    <nav class="navbar navbar-default top-nav">
            <div class="container-fluid cf">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                  </button>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse navcollaps" id="bs-example-navbar-collapse-1">
                  <ul class="nav navbar-nav top-nav-left">
                    <li><a href="#">Home <span class="bare-top-menu">|</span></a></li>
                    <li class="limf"><a href="#">About-company <span class="bare-top-menu">|</span></a></li>
                    <li class="limf"><a href="#">Payment-methods <span class="bare-top-menu">|</span></a></li>
                    <li class="limf"><a href="#">Contact</a></li>
                  </ul>
                  <ul class="nav navbar-nav navbar-right">
                    <li class="connexion"><a href="/customer/account"><div class="cadenas"></div>Connexion</a></li>
                    <li class="inscription"><a href="/customer/account/create"><div class="bonhom"></div>Inscription</a></li>
                    <li class="panier"><div class="caqul"></div><div class="cady"></div><a href="/checkout/cart"></a></li>
                  </ul>
                </div><!-- /.navbar-collapse -->                    
            </div><!-- /.container-fluid -->      
        </nav>
	</div>
    <ul class="navbar-right_bis">
      <li class="connexion_bis"><a href="/customer/account"><div class="cadenas cadenas_bis"></div>Connexion</a></li>
      <li class="inscription_bis"><a href="/customer/account/create"><div class="bonhom bonhom_bis"></div>Inscription</a></li>
      <li class="panier_bis"><div class="caqul"></div><div class="cady"></div><a href="/checkout/cart"></a></li>
    </ul>
  