<div class="content-custom-cms-page form-custom">
    <div id="messages_product_view"><?php echo $this->getMessagesBlock()->toHtml() ?></div>
    <div class="page-title">
        <h1><?php echo Mage::helper('phonereminder')->__('We remind to you') ?></h1>
    </div>
    <form action="<?php echo $this->getFormAction(); ?>" id="phonereminderForm" method="post">
        <div class="fieldset">
            <ul class="form-list">
                <li class="fields">
                    <label for="lastname" class="required"><em>*</em><?php echo Mage::helper('phonereminder')->__('Last name') ?> :</label>
                    <div class="input-box">
                        <input name="lastname" id="lastname" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('phonereminder')->__('Last name')) ?>" value="<?php echo $this->escapeHtml($this->helper('phonereminder')->getLastName()) ?>" class="input-text form-control required-entry" type="text" />
                    </div>
                </li>
                <li class="fields">
                    <label for="firstname" class="required"><em>*</em><?php echo Mage::helper('phonereminder')->__('First name') ?> :</label>
                    <div class="input-box">
                        <input name="firstname" id="firstname" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('phonereminder')->__('First name')) ?>" value="<?php echo $this->escapeHtml($this->helper('phonereminder')->getFirstName()) ?>" class="input-text form-control required-entry" type="text" />
                    </div>
                </li>
                <li>
                    <label for="telephone"><em>*</em><?php echo Mage::helper('phonereminder')->__('Telephone') ?> :</label>
                    <div class="input-box">
                        <input name="telephone" id="telephone" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('phonereminder')->__('Telephone')) ?>" value="" class="input-text form-control required-entry" type="text" />
                    </div>
                </li>
            </ul>
        </div>
        <div class="buttons-set">
            <p class="required"><?php echo Mage::helper('phonereminder')->__('* Required informations') ?></p>
            <input type="text" name="hideit" id="hideit" value="" style="display:none !important;" />
            <button type="submit" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('phonereminder')->__('Send the request of reminder')) ?>" class="button btn btn-success"><span><span><?php echo Mage::helper('phonereminder')->__('Send the request of reminder') ?></span></span></button>
        </div>
    </form>
    <script type="text/javascript">
        //<![CDATA[
        var phonereminderForm = new VarienForm('phonereminderForm', true);
        //]]>
    </script>
</div>
